Repository wrappid/native-web, pull requests merged in 2024-08, with the labels that each got.

#91 docs(core): :memo: update readme
  README.md
Labels: documentation

#92 feat(core): :sparkles: adding listType in CoreList
  package/nativeComponents/layouts/NativeList.js
Labels: enhancement

#94 feat(core): :sparkles: in corelist new varient props has been added
  package/nativeComponents/layouts/NativeList.js
Labels: enhancement, requirement-proposed

#98 fix(global): :bug: props.children wrap with div
  package/nativeComponents/dataDisplay/NativeTooltip.js
Labels: bug

#100 feat(global): :sparkles: add NativeClickAwayListner
  package/index.js
  package/nativeComponents/NativeClickAwayListner.js
Labels: enhancement

#102 fix(core): :bug: corelistitemsecondaryaction has been implemented
  package/index.js
  package/nativeComponents/dataDisplay/NativeListItemSecondaryAction.js
  package/styledComponents/dataDisplay/SCListItemSecondaryAction.js
Labels: bugfix

#96 bugfix: support for non react element CoreList
  package/nativeComponents/layouts/NativeList.js
Labels: bugfix

#104 feat(core): :zap: new utility function added
  package/index.js
  package/utils/app.utils.js
Labels: enhancement

#106 feat(global): :sparkles: pass dialogProps in SCDialog
  package/nativeComponents/feedback/NativeDialog.js
Labels: enhancement

#108 fix(global): :bug: export missing NativeFormControlLabel
  package/index.js
Labels: bug, bugfix

#110 fix(core): :bug: inputs/NativeInput default onChange added
  package/nativeComponents/inputs/NativeInput.js
Labels: bugfix

#113 fix(global): :bug: export missing NativeFormGroup
  package/index.js
  package/nativeComponents/inputs/NativeFormGroup.js
Labels: bug
