Repository wrappid/native-web, pull requests merged in 2024-10, with the labels that each got.

#138 feat(global): :sparkles: itemGridProps and itemItemProps props has been added to corelist
  package/nativeComponents/layouts/NativeList.js
Labels: enhancement, requirement-proposed

#149 enhancement: toolbox component
  package/index.js
  package/nativeComponents/surfaces/NativeToolBox.js
  package/styledComponents/surfaces/SCToolBox.js
Labels: enhancement

#151 feature(core): more than 2 icon replace with 3 dot
  package/nativeComponents/surfaces/NativeToolBox.js
  package/styledComponents/surfaces/SCToolBox.js
Labels: enhancement

#156 fix(global): :bug: fixed expand-collapse in toolbox
  package/nativeComponents/surfaces/NativeToolBox.js
Labels: bugfix
