Repository wrappid/native-web, pull requests merged in 2024-07, with the labels that each got.

#79 fix(core): :bug: native json editor fixed
  package/nativeComponents/inputs/NativeJSONEditor.js
Labels: bugfix

#81 docs(global): :memo: adding pull_request_template
  .github/pull_request_template.md
Labels: documentation

#83 fix(core): :bug: update code in NativeOtpInput to fix the issue
  package/nativeComponents/inputs/NativeOtpInput.js
Labels: bug, bugfix

#85 fix(core): :bug: add required checks
  package/nativeComponents/inputs/NativeOtpInput.js
Labels: bugfix

#87 style(utils): :art: change NativeImagePicker tooltip message
  package/nativeComponents/inputs/NativeImagePicker.js
Labels: enhancement

#88 fix(core): :bug: otp undefiend
  package/nativeComponents/inputs/NativeOtpInput.js
Labels: bug
