Repository wrappid/native-web, pull requests merged in 2024-09, with the labels that each got.

#115 feat(global): :sparkles: passing prop in LinearProgress
  package/nativeComponents/feedback/NativeLinearProgress.js
Labels: enhancement

#117 feat(global): :recycle: restructuring NativeDatepicker
  package/nativeComponents/inputs/NativeDatepicker.js
Labels: enhancement

#120 fix(core): :bug: inputs/NativeInput fix onChange
  package/nativeComponents/inputs/NativeInput.js
Labels: bug

#125 fix(global): :ambulance: fix NativeSelect, NativeMenuItem not working
  package/nativeComponents/inputs/NativeMenuItem.js
  package/nativeComponents/inputs/NativeSelect.js
Labels: bug, bugfix

#134 fix(global): :bug: fix miniDrawer as it not visible
  package/styledComponents/navigation/SCDrawer.js
Labels: bugfix

#129 fix(core): :bugfix: navigation/NativeLink props handling
  package/nativeComponents/navigation/NativeLink.js
Labels: bugfix

#131 feat(global): :sparkles: enabled has been implemented in gridProps
  package/nativeComponents/layouts/NativeGrid.js
Labels: enhancement

#135 feat(core): :zap: add default fullWidth
  package/nativeComponents/inputs/NativeFormControl.js
Labels: frontend-web
